language: node_js
dist: trusty

node_js:
  - "6"

#addons:
#  sonarqube:
#    token: $SONARQUBE_TOKEN

# install dependencies
before_script:
  - npm install -g gulp

script:
  - gulp ci
#  - sonar-scanner
